global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  # JMX collect JVM Metric
  - job_name: "jmx-customers"
    static_configs:
      - targets: ["customers-service:9901"]
    metrics_path: "/metrics" 


  - job_name: "jmx-vets"
    static_configs:
      - targets: ["vets-service:9911"]
    metrics_path: "/metrics" 

  # Telegraf
  - job_name: "node-gateway"
    static_configs:
      - targets: ["node-gateway:9100"]
    metrics_path: "/metrics"

  - job_name: "node-service"
    static_configs:
      - targets: ["node-service:9100"]
    metrics_path: "/metrics"


  # Jmeter
  - job_name: 'jmeter'
    static_configs:
      - targets: ['host.docker.internal:9270']
    metrics_path: "/metrics" 

  # Easeagent - metrics
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:9905"]
    metrics_path: "/prometheus/metrics" 
  - job_name: "visits-service"
    static_configs:
      - targets: ["visits-service:9903"]
    metrics_path: "/prometheus/metrics" 
  - job_name: "customers-service"
    static_configs:
      - targets: ["customers-service:9902"]
    metrics_path: "/prometheus/metrics" 
  - job_name: "vets-service"
    static_configs:
      - targets: ["vets-service:9904"]
    metrics_path: "/prometheus/metrics"  

