global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: "demo-employee"
    static_configs:
      - targets: ["host.docker.internal:9900"]
    metrics_path: "/prometheus/metrics" 
  - job_name: "demo-consumer"
    static_configs:
      - targets: ["host.docker.internal:9901"]
    metrics_path: "/prometheus/metrics" 
  - job_name: "demo-api"
    static_configs:
      - targets: ["host.docker.internal:9902"]
    metrics_path: "/prometheus/metrics" 
