global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  # JMX collect JVM Metric
  - job_name: "jmx-customers-agent"
    static_configs:
      - targets: ["customers-service-agent:9901"]
    metrics_path: "/metrics" 

  - job_name: "jmx-customers-origin"
    static_configs:
      - targets: ["customers-service-origin:9901"]
    metrics_path: "/metrics" 

  # Jmeter
  - job_name: 'jmeter'
    static_configs:
      - targets: ['host.docker.internal:9270']
    metrics_path: "/metrics" 

  # Easeagent - metrics
  - job_name: "agent-api-gateway"
    static_configs:
      - targets: ["api-gateway-agent:9905"]
    metrics_path: "/prometheus/metrics" 
  - job_name: "agent-visits-service"
    static_configs:
      - targets: ["visits-service-agent:9903"]
    metrics_path: "/prometheus/metrics" 
  - job_name: "agent-customers-service"
    static_configs:
      - targets: ["customers-service-agent:9902"]
    metrics_path: "/prometheus/metrics" 
  - job_name: "agent-vets-service"
    static_configs:
      - targets: ["vets-service-agent:9904"]
    metrics_path: "/prometheus/metrics"  

